//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMyOnlinShoppingEnities : DbContext
    {
        public dbMyOnlinShoppingEnities()
            : base("name=dbMyOnlinShoppingEnities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_cartStatus> Tbl_cartStatus { get; set; }
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
        public virtual DbSet<Tbl_MemberRole> Tbl_MemberRole { get; set; }
        public virtual DbSet<Tbl_Members> Tbl_Members { get; set; }
        public virtual DbSet<Tbl_Product> Tbl_Product { get; set; }
        public virtual DbSet<tbl_slideImage> tbl_slideImage { get; set; }
        public virtual DbSet<Tble_Cart> Tble_Cart { get; set; }
        public virtual DbSet<Tble_Roles> Tble_Roles { get; set; }
        public virtual DbSet<Tble_shipmentDetails> Tble_shipmentDetails { get; set; }
    }
}
