//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tble_Cart
    {
        public int Cart_Id { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> CartstatusId { get; set; }
    
        public virtual Tbl_Members Tbl_Members { get; set; }
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
